### ISSUE TITLE
Successfully deployed Wharf but it returns 500

### ISSUE THREAD

**Issue by PabloVSouza** [palfrey/wharf#111]
I'm trying to setup wharf for the first time on my VPS, and after following some guides, i have managed to successfully deploy the app, but when i try to access it, i get an error 500.
![image](https://user-images.githubusercontent.com/30412188/111486365-300b2880-8716-11eb-9e51-d4232431cef6.png)

After reading the logs, i could not find the source of this problem...
![image](https://user-images.githubusercontent.com/30412188/111486559-5af57c80-8716-11eb-8c15-fdbde65f9035.png)

It's probably some newbie mistake, but i have no clue on how to solve it...

**Comment by palfrey** [comment]
Not sure TBH. Looks like it's parsing something badly. What happens if you run `dokku config --global` on the server? Also, which version of Dokku are you running? If it's >0.19.13 then [as per the README](https://github.com/palfrey/wharf#setup) this won't work!

**Comment by PabloVSouza** [comment]
> Not sure TBH. Looks like it's parsing something badly. What happens if you run `dokku config --global` on the server? Also, which version of Dokku are you running? If it's >0.19.13 then [as per the README](https://github.com/palfrey/wharf#setup) this won't work!

It was the dokku version, thanks!
