### ISSUE TITLE
Google oauth2 Login

### ISSUE THREAD

**Issue by jyoost** [palfrey/wharf#123]
@palfrey 

I have the app (wharf) set up on on a vps running dokku.

i am getting the following error from google

Authorization Error
Error 400: redirect_uri_mismatch

You can't sign in to this app because it doesn't comply with Google's OAuth 2.0 policy.

If you're the app developer, register the redirect URI in the Google Cloud Console.
Learn more
Request Details
The content in this section has been provided by the app developer. This content has not been reviewed or verified by Google.
If you’re the app developer, make sure that these request details comply with Google policies.
redirect_uri: http://wharf.wonegraph.com/complete/google-oauth2/

I put https in the redirect_uri on google.

## Any Ideas?

**Comment by palfrey** [comment]
No idea how that's happened. Pretty sure it's not A Wharf issue as we don't use Oauth or Google login stuff at all!

**Comment by jyoost** [comment]
I have it straightened out now.  I merged in a branch from a PR on your repo.

At any rate very nice work,  I have it working now with the latest versions of the plugins.
