### ISSUE TITLE
App container failed to start!!

### ISSUE THREAD

**Issue by O-mkar** [palfrey/wharf#22]
Removing intermediate container 02364079ddba
 ---> ac1a82c2c0ed
Successfully built ac1a82c2c0ed
Successfully tagged dokku/wharf:latest
-----> Releasing wharf (dokku/wharf:latest)...
-----> Deploying wharf (dokku/wharf:latest)...
-----> Attempting to run scripts.dokku.predeploy from app.json (if defined)
-----> No Procfile found in app image
-----> DOKKU_SCALE file found (/home/dokku/wharf/DOKKU_SCALE)
=====> web=1
-----> Attempting pre-flight checks
       For more efficient zero downtime deployments, create a file CHECKS.
       See http://dokku.viewdocs.io/dokku/deployment/zero-downtime-deploys/ for examples
       CHECKS file not found in container: Running simple container check...
-----> Waiting for 10 seconds ...
remote: App container failed to start!!
=====> wharf web container output:
=====> end wharf web container output

**Comment by matt-goingout** [comment]
same:
-----> Attempting pre-flight checks
       For more efficient zero downtime deployments, create a file CHECKS.
       See http://dokku.viewdocs.io/dokku/deployment/zero-downtime-deploys/ for examples
       CHECKS file not found in container: Running simple container check...
-----> Waiting for 10 seconds ...
remote: App container failed to start!!
=====> wharf web container output:
=====> end wharf web container output

**Comment by matt-goingout** [comment]
docker-compose up locally works fine, and browsing to localhost:8000 presents the login screen (but obviously doesn't do much),  pushing the repo to a latest dokku results in above error (installed with sudo DOKKU_TAG=v0.12.13 bash bootstrap.sh)

**Comment by wesbos** [comment]
same here :\

**Comment by wesbos** [comment]
@palfrey any idea?

**Comment by palfrey** [comment]
Sorry, I've only just seen this. So, not sure yet. I'm running 0.11.3 locally, so that might work. The "No Procfile found in app image" is suspicious, as a) there is a Procfile and b) that would probably stop things from starting properly.

I'll try and spin up dokku fully locally again in a while, but I've got a fairly dodgy internet connection, so might be a bit.

**Comment by pedrofracassi** [comment]
Any fixes for this? I'm getting the same error.

**Comment by palfrey** [comment]
This should now be fixed by #34
