### ISSUE TITLE
Successfully deployed Wharf but it returns 500

### ISSUE THREAD

**Issue by Timtech4u** [palfrey/wharf#33]
Hi, I'd like to use Wharf on my server that runs dokku.
I keep getting a 500 error for the homepage, after login, and I can't find anything on the logs.
![image](https://user-images.githubusercontent.com/11256481/50827904-1c96f280-1340-11e9-89e4-7362d919974e.png)

Kindly help suggest fixes. Thanks

**Comment by thomasfedb** [comment]
Can you look in the logs using Dokku and find the error itself?

**Comment by palfrey** [comment]
@Timtech4u Can you retry now that #34 has been merged?

**Comment by IrregularShed** [comment]
I'm currently getting the exact same response :/ According to the Chrome dev tools, it's actually a 504 (Gateway timeout). I'm new to dokku, so I've been working through all the options I can think of. I guess with it being a timeout, and thinking about the issues I've seen in my own work in the past, there could be an issue with the way NGINX is connecting to Wharf?

**Comment by davipatury** [comment]
Might be related:
504 (Gateway timeout)
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/work/wharf/auth.py", line 75, in __call__
    if len(path) > 0 and is_safe_url(url=request.path_info, host=request.get_host()):
TypeError: is_safe_url() got an unexpected keyword argument 'host'
```

**Comment by palfrey** [comment]
I've just merged #36 which should fix the `is_safe_url` issue if that's the problem here

**Comment by sataloger** [comment]
Got the same problem with timeouts in nginx - in my case it was caused by non-started celery worker.
As it is said in [docs](http://dokku.viewdocs.io/dokku/deployment/process-management/):
```
By default, Dokku will only start a single web process - if defined - though process 
scaling can be managed by the ps plugin or via a custom DOKKU_SCALE file.
```

So this was a quick solution for me
```
dokku ps:scale wharf celery=1
```

**Comment by palfrey** [comment]
I've just fixed the scaling issues with #37, which along the way also spotted an issue with Paramiko and first-time boots that might also be causing this...

**Comment by Timtech4u** [comment]
Great, thanks @palfrey , I've been able to get past this with your updates.

However, I'm currently stuck here, even after I've added the ssh keys.
![image](https://user-images.githubusercontent.com/11256481/52199285-f0e72980-2865-11e9-8e26-da9aacbb4a4d.png)

My log says something about Paramiko unable to connect on 127.0.0.1
![Uploading image.png…]()

**Comment by palfrey** [comment]
Looks like you've hit #6 which I still need to look at...

**Comment by IrregularShed** [comment]
Yep, I've got the same issue as @Timtech4u, with the ssh key looping around. One step closer though.

And can I add - thanks @palfrey for your efforts, I really appreciate it!

**Comment by Timtech4u** [comment]
Cool @palfrey, awesome work you're doing.

**Comment by palfrey** [comment]
There was a variety of issues with first SSH key adding and initial app work. OTOH, #38 (now merged) tests that path, and helped me find various issues, so maybe I can close out this ticket now as well?

**Comment by Timtech4u** [comment]
Hi @palfrey , thanks for the fix. It works!
I just removed the ssh key, re-added it and click on the link to reload..
I'll go ahead and close this now 👍
