### ISSUE TITLE
Login keeps asking me to add SSH Key

### ISSUE THREAD

**Issue by robertorubioguardia** [palfrey/wharf#42]
Hi and thanks a lot for this app.

For some reason I cant determine, the app keeps asking me to set the SSH key each time I deploy. I thought it could be the key was not being persisted in some way, so I checked the storage mount suggested in the instructions and its blank.

any hints?

**Comment by palfrey** [comment]
Can you provide the output of `dokku log wharf`?

**Comment by palfrey** [comment]
Prodded this a bit, and found out the path was wrong. #43 fixes this, but if you use `/root/.ssh` rather than `/app/.ssh` it should fix it.

**Comment by robertorubioguardia** [comment]
Thans a lot! 




Cheers. 




R. 




Get Outlook for Android







On Fri, Feb 22, 2019 at 1:39 PM -0500, "Tom Parker-Shemilt" <notifications@github.com> wrote:












Prodded this a bit, and found out the path was wrong. #43 fixes this, but if you use /root/.ssh rather than /app/.ssh it should fix it.
