### ISSUE TITLE
Need an option to clear build history/wipe logs

### ISSUE THREAD

**Issue by seiyria** [palfrey/wharf#72]
After a few months of using Wharf, something generally just breaks and it refuses to deploy my app anymore, resulting in me needing to do a full deploy of wharf again, from scratch. Otherwise all of my tasks sit in `PENDING`.

**Comment by palfrey** [comment]
If something non-specific is breaking, I'm not sure how wiping the build history would fix this? I'm guessing it's gotten in a wedged state somehow. Can you provide any more logs on the broken states?

**Comment by seiyria** [comment]
It looks like wharf is actually running out of memory periodically, likely while building my app and deploying it. But, sometimes the deploys do just end up pending forever and I have to restart wharf and force a redeploy of the app and that will seem to unstuck it. Sadly, no logs to share because they don't get very far. I can update this if I find a more specific, reproducible case though.

**Comment by palfrey** [comment]
Yeah, the out-of-memory cases aren't really tested well TBH, as I'd mostly file them under "give it more memory", and also that making this OOM-resistant would be pretty hard given the large set of other tooling buried underneath it. If you (or anyone else) has any bright ideas about how to improve that though, I'm happy to see patches for it.

**Comment by palfrey** [comment]
Please re-open if you've got failure logs
