### ISSUE TITLE
django-celery issue?

### ISSUE THREAD

**Issue by dcalixto** [palfrey/wharf#86]
First, thank you for the work!
After setup, everything went ok!
But the app did not start, seems to cause 500 error

![wharf-1](https://user-images.githubusercontent.com/1009077/81309198-0e063b80-9059-11ea-8b28-5766683f0c10.png)

![wharf-2](https://user-images.githubusercontent.com/1009077/81309217-12caef80-9059-11ea-8e1c-ba90777b4a9f.png)

**Comment by palfrey** [comment]
Hmm. Can you get any more logs of the 500 itself? The celery stuff you posted is slightly alarming, but has been like that for ages.

**Comment by dcalixto** [comment]
@palfrey sorry! and thank you very much for your reply! forget to setup the dns to wildcard so everything is ok!
just one doubt is necessary to setup another ssh-key to wharf?

![key](https://user-images.githubusercontent.com/1009077/81312567-28daaf00-905d-11ea-83f8-c33649c26e55.png)

**Comment by palfrey** [comment]
Have you done the `ssh-keys:add` for Wharf already? It has it's own SSH key it generates in order to isolate it and make sure it's just got access to the Dokku instance it's meant to have.

**Comment by palfrey** [comment]
Closing now due to lack of response, but please reopen if there's still an issue
